# Generated by Django 2.2.7 on 2019-11-19 16:33

import dashboard.helper_functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('node_id', models.IntegerField()),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('product_code_type', models.CharField(choices=[('upc', 'UPC')], max_length=100)),
                ('multipack_quantity', models.IntegerField()),
                ('main_image_url', models.FileField(upload_to=dashboard.helper_functions.user_directory_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Brands')),
            ],
        ),
    ]
