# Generated by Django 2.2.7 on 2019-11-19 16:55

import dashboard.helper_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191119_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.helper_functions.user_directory_path),
        ),
    ]
